#!/bin/bash
set -e

# ============================================
# ComrcexFlow - DigitalOcean Droplet Deploy
# Run this script on a fresh Docker Droplet
# ============================================

echo "=========================================="
echo " ComrcexFlow Deployment Script"
echo "=========================================="

# Get the server's public IP
SERVER_IP=$(curl -s ifconfig.me)
APP_DOMAIN="${SERVER_IP}.sslip.io"

echo ""
echo "Detected IP: ${SERVER_IP}"
echo "App Domain:  ${APP_DOMAIN}"
echo "App URL:     https://${APP_DOMAIN}"
echo ""

# Clone the repo
echo "==> Cloning repository..."
cd /root
if [ -d "comrcexflow" ]; then
    cd comrcexflow
    git pull origin master
else
    git clone https://github.com/AB254/Comrcexflow.git comrcexflow
    cd comrcexflow
fi

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -hex 16)
INTERNAL_WORKER_SECRET=$(openssl rand -hex 32)

# Prompt for Shopify credentials
echo ""
echo "==> Enter your Shopify app credentials"
echo ""
read -p "SHOPIFY_API_KEY (Client ID): " SHOPIFY_API_KEY
read -p "SHOPIFY_API_SECRET (Client Secret): " SHOPIFY_API_SECRET
read -p "MASTER_BYPASS_KEY (your dev key): " MASTER_BYPASS_KEY

# Create .env file
echo ""
echo "==> Creating .env file..."
cat > .env << EOF
# Auto-generated by deploy.sh on $(date)
APP_DOMAIN=${APP_DOMAIN}
SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
SHOPIFY_APP_URL=https://${APP_DOMAIN}
HOST=https://${APP_DOMAIN}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_URL=redis://redis:6379
DATABASE_URL=postgresql://comrcexflow:${POSTGRES_PASSWORD}@postgres:5432/comrcexflow?schema=public
MASTER_BYPASS_KEY=${MASTER_BYPASS_KEY}
INTERNAL_WORKER_SECRET=${INTERNAL_WORKER_SECRET}
NODE_ENV=production
SCOPES=write_products,read_orders,write_orders,read_checkouts,write_checkouts,read_customers
EOF

echo "==> .env created"

# Open firewall ports
echo "==> Configuring firewall..."
ufw allow 80/tcp 2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true

# Build and start
echo ""
echo "==> Building and starting services (this takes 5-10 minutes on first run)..."
docker compose -f docker-compose.prod.yml up -d --build

echo ""
echo "==> Waiting for services to start..."
sleep 10

# Check status
echo ""
echo "==> Service status:"
docker compose -f docker-compose.prod.yml ps

echo ""
echo "=========================================="
echo " DEPLOYMENT COMPLETE!"
echo "=========================================="
echo ""
echo " App URL:     https://${APP_DOMAIN}"
echo " App Domain:  ${APP_DOMAIN}"
echo " Server IP:   ${SERVER_IP}"
echo ""
echo " IMPORTANT: Update your Shopify Partner Dashboard:"
echo ""
echo " App URL:               https://${APP_DOMAIN}/app"
echo " Redirect URL:          https://${APP_DOMAIN}/auth/callback"
echo " Redirect URL:          https://${APP_DOMAIN}/auth/shopify/callback"
echo " Redirect URL:          https://${APP_DOMAIN}/api/auth/callback"
echo " Customer deletion:     https://${APP_DOMAIN}/webhooks"
echo " Customer data request: https://${APP_DOMAIN}/webhooks"
echo " Shop deletion:         https://${APP_DOMAIN}/webhooks"
echo ""
echo " View logs:  docker compose -f docker-compose.prod.yml logs -f"
echo " Stop:       docker compose -f docker-compose.prod.yml down"
echo " Restart:    docker compose -f docker-compose.prod.yml restart"
echo "=========================================="
