# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c7c620214c5d83ebe07b6eb4376c58b"
name = "ComrcexFlow"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "comrcexflow-wa"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  # NOTE: Uncomment these after protected customer data access is approved
  # [[webhooks.subscriptions]]
  # topics = ["orders/create", "orders/cancelled", "orders/fulfilled"]
  # uri = "/webhooks"

  # [[webhooks.subscriptions]]
  # topics = ["checkouts/update"]
  # uri = "/webhooks"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks"
  customer_data_request_url = "/webhooks"
  shop_deletion_url = "/webhooks"

[access_scopes]
scopes = "write_products,read_orders,write_orders,read_checkouts,write_checkouts,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
