# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c7c620214c5d83ebe07b6eb4376c58b"
name = "ComrcexFlow"
application_url = "https://134.209.123.46.sslip.io"
embedded = true
handle = "comrcexflow-wa"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_orders,write_checkouts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://134.209.123.46.sslip.io/auth/callback",
  "https://134.209.123.46.sslip.io/auth/shopify/callback",
  "https://134.209.123.46.sslip.io/api/auth/callback"
]

[pos]
embedded = false
